apiVersion: 1

datasources:
  - name: Prometheus-Measurement
    type: prometheus
    uid: prometheus-measurement
    access: proxy
    url: http://localhost:9099
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s