global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    machine: local-lab
    purpose: energy-measurement

scrape_configs:
  - job_name: scaphandre
    params:
      collect[]:
        - energy
    fallback_scrape_protocol: PrometheusText0.0.4
    static_configs:
      - targets: ["localhost:8083"]
        labels:
          measurement_tool: scaphandre

