global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    machine: local-lab
    purpose: energy-measurement

scrape_configs:
  - job_name: scaphandre
    fallback_scrape_protocol: PrometheusText0.0.4
    static_configs:
      - targets: ["localhost:8083"]
        labels:
          measurement_tool: scaphandre

  - job_name: alumet
    static_configs:
      - targets: ["localhost:9091"]
        labels:
          measurement_tool: alumet

  - job_name: kepler
    static_configs:
      - targets: ["localhost:8085"]
        labels:
          measurement_tool: kepler
